version: '3.9'

services:
  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch:8.4.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.4.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data:
  mongodb_data: